on:
  push:
    paths:
      - "src/**"
      - "@RepositoryName.sln"
      - ".github/workflows/test-template.yml"

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  build-commit:
    name: Replace Variables on Commit ${{ github.sha }}
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Replace Variables
        run: tools/replace-variables.sh "${{ github.event.repository.name }}" "${{ github.event.repository.description }}"
      - name: Find unused variables
        continue-on-error: true
        run: grep -rFl --exclude-dir=tools --exclude-dir=.git "@" . && echo "Unused variables found." && exit 1
  test-commit:
      name: Build Commit ${{ github.sha }}
      runs-on: ubuntu-latest
      needs: build-commit
      steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Build Project
        run: dotnet build
      - name: Build Dockerfile
        run: docker build -t ${{ github.event.repository.name }}:latest .